name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build bundle
        run: make release

      - name: Get version
        id: version
        run: echo "version=$(defaults read "$PWD"/src/info.plist version)" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: fakeum-v${{ steps.version.outputs.version }}.alfredworkflow
